from pathlib import Path


APP_NAME = 'HotPOS'
VERSION = 1

ROOT_PATH = Path(__file__).parent.parent
RES_PATH = ROOT_PATH / 'res'

WINDOW_MIN_SIZE = (1440, 800)
MAIN_CAT_ICON_SIZE = (48, 48)
MAIN_CAT_LIST_WIDTH = 128
SUB_CAT_LIST_HEIGHT = 32
ITEM_ICON_SIZE = (180, 120)
SIZE_A = 24
SIZE_B = 40
SIZE_C = 96
